Repository sproutt/eussya-eussya-api, pull requests merged in 2020-03, with the labels that each got.

#29 Travis를 활용한 CI 구축 (최종)
  .coveralls.yml
  .travis.yml
  Dockerfile
  README.md
  appspec.yml
  build.gradle
  execute-deploy.sh
  system.properties
Labels: enhancement

#24 이메일 본인 인증 구현
  .travis.yml
  build.gradle
  src/main/java/com/sproutt/eussyaeussyaapi/api/config/WebConfig.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/dto/EmailDTO.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/dto/ErrorResponse.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/dto/ValidateError.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/exception/GlobalExceptionHandler.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/member/MemberController.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/member/dto/JoinDTO.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/member/dto/LoginDTO.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/security/JwtInterceptor.java
  src/main/java/com/sproutt/eussyaeussyaapi/application/MailService.java
  src/main/java/com/sproutt/eussyaeussyaapi/application/MailServiceImpl.java
  src/main/java/com/sproutt/eussyaeussyaapi/application/member/MemberServiceImpl.java
  src/main/java/com/sproutt/eussyaeussyaapi/domain/member/Member.java
  src/main/java/com/sproutt/eussyaeussyaapi/domain/member/exceptions/DuplicatedMemberIdException.java
  src/main/java/com/sproutt/eussyaeussyaapi/domain/member/exceptions/DuplicationMemberException.java
  src/main/java/com/sproutt/eussyaeussyaapi/domain/member/exceptions/NoSuchMemberException.java
  src/main/java/com/sproutt/eussyaeussyaapi/domain/member/exceptions/WrongPasswordException.java
  src/main/java/com/sproutt/eussyaeussyaapi/utils/ExceptionMessage.java
  src/main/java/com/sproutt/eussyaeussyaapi/utils/RandomGenerator.java
  src/main/java/com/sproutt/eussyaeussyaapi/utils/RegexExpression.java
  src/main/resources/application.yml
  src/main/resources/messages.properties
  src/test/java/com/sproutt/eussyaeussyaapi/acceptance/MemberAcceptanceTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/api/MemberControllerTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/api/exception/GlobalExceptionHanlderTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/application/MailServiceTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/application/MemberServiceTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/utils/RandomGeneratorTest.java
Labels: enhancement

#34 [Bug] 배포 도중 오류 문제 해결
  .travis.yml
Labels: bug

#35 멤버 테이블 수정 및 로직 변경 (#31)
  src/main/java/com/sproutt/eussyaeussyaapi/api/config/WebConfig.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/dto/EmailDTO.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/exception/GlobalExceptionHandler.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/member/EmailAuthDTO.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/member/MemberController.java
  src/main/java/com/sproutt/eussyaeussyaapi/application/member/MemberService.java
  src/main/java/com/sproutt/eussyaeussyaapi/application/member/MemberServiceImpl.java
  src/main/java/com/sproutt/eussyaeussyaapi/domain/member/Member.java
  src/main/java/com/sproutt/eussyaeussyaapi/domain/member/Provider.java
  src/main/java/com/sproutt/eussyaeussyaapi/domain/member/exceptions/VerificationException.java
  src/main/java/com/sproutt/eussyaeussyaapi/utils/ExceptionMessage.java
  src/main/java/com/sproutt/eussyaeussyaapi/utils/RegexExpression.java
  src/test/java/com/sproutt/eussyaeussyaapi/acceptance/MemberAcceptanceTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/api/MemberControllerTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/application/MemberServiceTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/utils/RegexExpressionTest.java
Labels: enhancement

#36 oauth2관련 로그인 구현 (#15)
  src/main/java/com/sproutt/eussyaeussyaapi/EussyaEussyaApiApplication.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/exception/GlobalExceptionHandler.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/oauth2/SocialController.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/oauth2/dto/FacebookOAuth2UserDto.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/oauth2/dto/GithubOAuth2UserDto.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/oauth2/dto/GoogleOAuth2UserDto.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/oauth2/exception/NotFoundOAuth2Exception.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/oauth2/exception/OAuth2CommunicationException.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/oauth2/exception/UnSupportOAuth2Exception.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/oauth2/service/FacebookOAuth2Service.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/oauth2/service/GithubOAuth2Service.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/oauth2/service/GoogleOAuth2Service.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/oauth2/service/OAuth2Service.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/oauth2/service/OAuth2ServiceFactory.java
  src/main/java/com/sproutt/eussyaeussyaapi/api/security/JwtInterceptor.java
  src/main/java/com/sproutt/eussyaeussyaapi/domain/member/Member.java
  src/main/java/com/sproutt/eussyaeussyaapi/domain/member/MemberRepository.java
  src/main/java/com/sproutt/eussyaeussyaapi/utils/ExceptionMessage.java
  src/main/resources/application.yml
  src/test/java/com/sproutt/eussyaeussyaapi/acceptance/SocialAcceptanceTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/application/GithubOAuth2ServiceTest.java
Labels: enhancement

#41 Member email 칼럼 추가 (#40)
  src/main/java/com/sproutt/eussyaeussyaapi/application/member/MemberServiceImpl.java
  src/main/java/com/sproutt/eussyaeussyaapi/domain/member/Member.java
  src/main/resources/messages.properties
  src/test/java/com/sproutt/eussyaeussyaapi/acceptance/SocialAcceptanceTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/api/MemberControllerTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/application/GithubOAuth2ServiceTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/application/MemberServiceTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/object/MemberFactory.java
Labels: enhancement

#43 [Bug] Cors 문제
  src/main/java/com/sproutt/eussyaeussyaapi/api/config/WebConfig.java
Labels: bug

#49 Jasypt를 활용한 Property 암호화(#46)
  build.gradle
  src/main/java/com/sproutt/eussyaeussyaapi/EussyaEussyaApiApplication.java
  src/main/java/com/sproutt/eussyaeussyaapi/config/JasyptConfig.java
  src/main/resources/application.yml
  src/test/java/com/sproutt/eussyaeussyaapi/acceptance/SocialAcceptanceTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/application/GithubOAuth2ServiceTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/config/JasyptTest.java
  src/test/java/com/sproutt/eussyaeussyaapi/object/EncryptedResourceGenerator.java
Labels: backend, enhancement
